version: '3'

services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning 
    volumes: 
      - cache:/data
  database:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db
  service-entity-user:
    build: 
      context: .
      dockerfile: ./apps/services/entity/user/Dockerfile
    volumes:
      - ./dist/apps/services/entity/user:/app
      - ./node_modules:/app/node_modules
    environment:
      - NODE_ENV=production
    depends_on:
      - cache
      - database
  service-entity-client:
    build: 
      context: .
      dockerfile: ./apps/services/entity/client/Dockerfile
    volumes:
      - ./dist/apps/services/entity/client:/app
      - ./node_modules:/app/node_modules
    environment:
      - NODE_ENV=production
    depends_on:
      - cache
      - database
  service-entity-customer:
    build: 
      context: .
      dockerfile: ./apps/services/entity/customer/Dockerfile
    volumes:
      - ./dist/apps/services/entity/customer:/app
      - ./node_modules:/app/node_modules
    environment:
      - NODE_ENV=production
    depends_on:
      - cache
      - database

  service-bff-authentication:
    build: 
      context: .
      dockerfile: ./apps/services/bff/authentication/Dockerfile
    volumes:
      - ./dist/apps/services/bff/authentication:/app
      - ./node_modules:/app/node_modules
    environment:
      - NODE_ENV=production
    depends_on:
      - cache
      - database
      - service-entity-user
      - service-entity-client
      - service-entity-customer
    ports:
        - "3000:3000"
      

volumes:
  cache:
    driver: local