version: '3'

services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
  database:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db
  api:
    build: 
      context: .
      dockerfile: ./apps/services/main/api/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./dist/apps/services/main/api:/app
      - ./node_modules:/app/node_modules
    environment:
      - NODE_ENV=production
    depends_on:
      - cache
      - database
volumes:
  cache:
    driver: local